name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

  export-database:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1
      with:
        mysql database: studentbehaviorreportdatabase
        mysql user: root
        mysql password: root_password

    - name: Export database
      run: |
        mysqldump -u root -proot_password --databases studentbehaviorreportdatabase > studentbehaviorreportdatabase_dump.sql
        git add studentbehaviorreportdatabase_dump.sql
        git commit -m "Update database dump"
        git push origin main
